/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { UserProfile } from "./userProfile";
import type { UserScore } from "./userScore";
import type { UserCommunity } from "./userCommunity";
import type { Community } from "./community";
import type { CommunityPost } from "./communityPost";
import type { StringIdentityUserRole } from "./stringIdentityUserRole";
import type { StringIdentityUserClaim } from "./stringIdentityUserClaim";

export interface ApplicationUser {
   id?: string | null;
   userName?: string | null;
   normalizedUserName?: string | null;
   email?: string | null;
   normalizedEmail?: string | null;
   emailConfirmed?: boolean;
   passwordHash?: string | null;
   securityStamp?: string | null;
   concurrencyStamp?: string | null;
   phoneNumber?: string | null;
   phoneNumberConfirmed?: boolean;
   twoFactorEnabled?: boolean;
   lockoutEnd?: string | null;
   lockoutEnabled?: boolean;
   accessFailedCount?: number;
   firstName: string;
   lastName: string;
   profile?: UserProfile;
   score?: UserScore;
   createdOn?: string;
   modifiedOn?: string | null;
   isDeleted?: boolean;
   deletedOn?: string | null;
   communities?: UserCommunity[] | null;
   communitiesAdministrated?: Community[] | null;
   communityPosts?: CommunityPost[] | null;
   roles?: StringIdentityUserRole[] | null;
   claims?: StringIdentityUserClaim[] | null;
}
