/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { JwtToken } from "./jwtToken";

export interface AuthenticationResultSuccessModel {
   userId?: string | null;
   token?: JwtToken;
}
