/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { Community } from "./community";
import type { Tag } from "./tag";

export interface CommunityTag {
   communityId: string;
   community?: Community;
   tagId: string;
   tag?: Tag;
}
