/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { CommunityDetailsAdminModel } from "./communityDetailsAdminModel";
import type { CommunityType } from "./communityType";

export interface CommunityDetailsModel {
   admin?: CommunityDetailsAdminModel;
   type?: CommunityType;
   name?: string | null;
   description?: string | null;
   pictureUrl?: string | null;
   picturePublicId?: string | null;
   hasUserJoined?: boolean;
   tags?: string[] | null;
   membersCount?: number;
   createdOn?: string;
}
