/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { PostComment } from "./postComment";
import type { ApplicationUser } from "./applicationUser";
import type { VoteType } from "./voteType";

export interface CommentVote {
   id?: string | null;
   createdOn?: string;
   modifiedOn?: string | null;
   isDeleted?: boolean;
   deletedOn?: string | null;
   commentId: string;
   comment?: PostComment;
   userId: string;
   user?: ApplicationUser;
   type: VoteType;
}
