/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { UserVoteModel } from "./userVoteModel";

export interface CommunityPostModel {
   id?: string | null;
   communityId?: string | null;
   authorId?: string | null;
   authorUserName?: string | null;
   mediaUrl?: string | null;
   mediaPublicId?: string | null;
   createdOn?: string;
   modifiedOn?: string | null;
   title?: string | null;
   content?: string | null;
   voteScore?: number;
   userVote?: UserVoteModel;
   commentsCount?: number;
   tags?: string[] | null;
}
