/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */

export interface CommunitySearchModel {
   id?: string | null;
   name?: string | null;
   description?: string | null;
   membersCount?: number;
   pictureUrl?: string | null;
   picturePublicId?: string | null;
   tags?: string[] | null;
   hasUserJoined?: boolean;
}
