/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { UserCommunity } from "./userCommunity";
import type { ApplicationUser } from "./applicationUser";
import type { CommunityType } from "./communityType";
import type { CommunityTag } from "./communityTag";
import type { CommunityPost } from "./communityPost";

export interface Community {
   id?: string | null;
   createdOn?: string;
   modifiedOn?: string | null;
   isDeleted?: boolean;
   deletedOn?: string | null;
   members?: UserCommunity[] | null;
   adminId: string;
   admin?: ApplicationUser;
   type: CommunityType;
   name: string;
   description?: string | null;
   pictureUrl: string;
   picturePublicId: string;
   tags?: CommunityTag[] | null;
   posts?: CommunityPost[] | null;
}
