/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { ApplicationUser } from "./applicationUser";
import type { Community } from "./community";
import type { PostVote } from "./postVote";
import type { PostComment } from "./postComment";
import type { PostTag } from "./postTag";

export interface CommunityPost {
   id?: string | null;
   createdOn?: string;
   modifiedOn?: string | null;
   isDeleted?: boolean;
   deletedOn?: string | null;
   authorId: string;
   author?: ApplicationUser;
   communityId: string;
   community?: Community;
   mediaUrl?: string | null;
   mediaPublicId: string;
   title: string;
   content: string;
   voteScore: number;
   votes?: PostVote[] | null;
   comments?: PostComment[] | null;
   tags?: PostTag[] | null;
}
