/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */

export type CommunityType = typeof CommunityType[keyof typeof CommunityType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommunityType = {
   "1": 1,
   "2": 2,
   "3": 3,
} as const;
