/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { TimeRange } from "./timeRange";

export type GetApiPostFeedTopParams = { range?: TimeRange };
