/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */

export interface PostSearchModel {
   id?: string | null;
   title?: string | null;
   content?: string | null;
   authorUserName?: string | null;
   authorId?: string | null;
   communityId?: string | null;
   communityName?: string | null;
   communityPictureUrl?: string | null;
   communityPicturePublicId?: string | null;
   voteScore?: number;
   commentsCount?: number;
   mediaUrl?: string | null;
   mediaPublicId?: string | null;
   createdOn?: string;
   modifiedOn?: string | null;
}
