/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { PostCommentAuthorModel } from "./postCommentAuthorModel";
import type { UserVoteModel } from "./userVoteModel";

export interface PostCommentDetailsModel {
   author?: PostCommentAuthorModel;
   content?: string | null;
   createdOn?: string;
   modifiedOn?: string | null;
   voteScore?: number;
   userVote?: UserVoteModel;
}
