/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { CommunityPost } from "./communityPost";
import type { Tag } from "./tag";

export interface PostTag {
   postId: string;
   post?: CommunityPost;
   tagId: string;
   tag?: Tag;
}
