/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */

export interface PostCommentAuthorModel {
   id?: string | null;
   userName?: string | null;
   profilePictureUrl?: string | null;
   profilePicturePublicId?: string | null;
}
