/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */

export interface ProblemDetails {
   type?: string | null;
   title?: string | null;
   status?: number | null;
   detail?: string | null;
   instance?: string | null;
   [key: string]: unknown;
}
