/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */

export type PutApiPostsBody = {
   PostId: string;
   Title: string;
   Content: string;
   Tags?: string[];
   Media?: Blob;
};
