/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */

export type PutApiUsersBody = {
   FirstName?: string;
   LastName?: string;
   Gender?: string;
   Country: string;
   AboutContent: string;
   Picture?: Blob;
};
