/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */

export interface StringIdentityUserClaim {
   id?: number;
   userId?: string | null;
   claimType?: string | null;
   claimValue?: string | null;
}
