/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */

export interface StringIdentityUserRole {
   userId?: string | null;
   roleId?: string | null;
}
