/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */

export interface Tag {
   id?: string | null;
   createdOn?: string;
   modifiedOn?: string | null;
   name: string;
}
