/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */

export type TimeRange = typeof TimeRange[keyof typeof TimeRange];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimeRange = {
   "1": 1,
   "2": 2,
   "3": 3,
   "4": 4,
   "5": 5,
   "6": 6,
} as const;
