/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { Gender } from "./gender";

export interface UserProfileModel {
   pictureUrl?: string | null;
   picturePublicId?: string | null;
   aboutContent?: string | null;
   gender?: Gender;
   countryName?: string | null;
   countryCode?: string | null;
}
