/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { VoteType } from "./voteType";

export interface UserVoteModel {
   id?: string | null;
   type?: VoteType;
}
