/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */

export type UserCommunityStatus =
   typeof UserCommunityStatus[keyof typeof UserCommunityStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserCommunityStatus = {
   "1": 1,
   "2": 2,
} as const;
