/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { ApplicationUser } from "./applicationUser";

export interface UserScore {
   id?: string | null;
   user?: ApplicationUser;
   postsScore?: number;
   commentsScore?: number;
}
