/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */
import type { ApplicationUser } from "./applicationUser";
import type { Gender } from "./gender";
import type { Country } from "./country";

export interface UserProfile {
   id?: string | null;
   createdOn?: string;
   modifiedOn?: string | null;
   isDeleted?: boolean;
   deletedOn?: string | null;
   userId: string;
   user?: ApplicationUser;
   profilePictureUrl: string;
   profilePicturePublicId: string;
   aboutContent?: string | null;
   gender?: Gender;
   countryId?: string | null;
   country: Country;
}
