/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */

export interface UserCommunityModel {
   id?: string | null;
   name?: string | null;
   pictureUrl?: string | null;
   picturePublicId?: string | null;

   membersCount: number;
}
