/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Readdit
 * OpenAPI spec version: v1
 */

export type VoteType = typeof VoteType[keyof typeof VoteType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoteType = {
   "0": 0,
   "1": 1,
} as const;
